# Imports:
from pathlib import Path
from openai import OpenAI
from dotenv import load_dotenv
from pydantic import BaseModel, Field
from chromadb import PersistentClient
from tqdm import tqdm
from litellm import completion
from tenacity import retry, wait_exponential

load_dotenv(override= True)

# Constants:
MODEL = 'llama3.1:8b'
DB_NAME = str(Path(__file__).parent.parent / 'preprocessed_db')
collection_name = 'docs'
embedding_model = 'text-embedding-3-large'
KNOWLEDGE_BASE_PATH = Path(__file__).parent.parent / 'knowledge_base'
wait = wait_exponential(multiplier= 1, min= 10, max= 240)


class Result(BaseModel):
    """
    Represents a final, processed chunk of documentation ready for the vector database.

    Attributes:
        page_content (str): The concatenated text containing the LLM-generated headline,
                            the LLM-generated summary, and the original untouched markdown text.
        metadata (dict): Contextual tags for the chunk. Will include 'source' (file path),
                         'type' (folder category), and the hierarchical Markdown headers
                         extracted during splitting.
    """
    page_content: str
    metadata: dict

class Chunk(BaseModel):
    """
        Represents the structured output expected from the local LLM.

        The LLM's only job is to analyze a provided section of Markdown text and generate a descriptive headline and summary.
        It does not reproduce the original text, which saves generation time and prevents code block corruption.
    """
    headline: str = Field(
        description= 'A brief heading for this chunk, typically a few words, that is most likely to be surfaced in a query'
    )
    summary: str = Field(
        description= 'A few sentences summarizing the content of this chunk to answer common questions'
    )

    def as_result(self, original_text: str, source_metadata: dict) -> Result:
        """
        Combines the LLM-generated insights with the original Markdown text
        to create a final Result object for the vector database.

        :param original_text: The untouched Markdown chunk from the text splitter.
        :param source_metadata: The dictionary containing the file source, type,
                                    and LangChain-extracted headers.

        :return: Result Object
        """

        # Combining Headline and Summary generated by LLM to Original Text of the Page
        full_content = f'{self.headline}\n\n{self.summary}\n\n{self.original_text}'

        return Result(
            page_content = full_content,
            metadata = source_metadata,
        )