# Imports:
from pathlib import Path
import os
import json
from langchain_text_splitters import MarkdownHeaderTextSplitter
from openai import OpenAI
from dotenv import load_dotenv
from pydantic import BaseModel, Field
from chromadb import PersistentClient
from tqdm import tqdm
from litellm import completion
from tenacity import retry, wait_exponential

load_dotenv(override= True)

# Constants:
MODEL = 'ollama/llama3.1:8b'
DB_NAME = str(Path(__file__).parent.parent / 'preprocessed_db')
collection_name = 'docs'
embedding_model = 'text-embedding-3-large'
KNOWLEDGE_BASE_PATH = Path(__file__).parent.parent / 'Knowledge-Base'
wait = wait_exponential(multiplier= 1, min= 10, max= 240)
ollama = OpenAI(base_url= os.getenv("OLLAMA_BASE_URL"), api_key= '')

class Result(BaseModel):
    """
    Represents a final, processed chunk of documentation ready for the vector database.

    Attributes:
        page_content (str): The concatenated text containing the LLM-generated headline,
                            the LLM-generated summary, and the original untouched markdown text.
        metadata (dict): Contextual tags for the chunk. Will include 'source' (file path),
                         'type' (folder category), and the hierarchical Markdown headers
                         extracted during splitting.
    """
    page_content: str
    metadata: dict

class Chunk(BaseModel):
    """
        Represents the structured output expected from the local LLM.

        The LLM's only job is to analyze a provided section of Markdown text and generate a descriptive headline and summary.
        It does not reproduce the original text, which saves generation time and prevents code block corruption.
    """
    headline: str = Field(
        description= 'A brief heading for this chunk, typically a few words, that is most likely to be surfaced in a query'
    )
    summary: str = Field(
        description= 'A few sentences summarizing the content of this chunk to answer common questions'
    )

    def as_result(self, original_text: str, source_metadata: dict) -> Result:
        """
        Combines the LLM-generated insights with the original Markdown text
        to create a final Result object for the vector database.

        :param original_text: The untouched Markdown chunk from the text splitter.
        :param source_metadata: The dictionary containing the file source, type,
                                    and LangChain-extracted headers.

        :return: Result Object
        """

        # Combining Headline and Summary generated by LLM to Original Text of the Page
        full_content = f'{self.headline}\n\n{self.summary}\n\n{original_text}'

        return Result(
            page_content = full_content,
            metadata = source_metadata,
        )

def fetch_document():

    documents = []

    for folder in KNOWLEDGE_BASE_PATH.iterdir():
        doc_type = folder.name
        for file in folder.rglob('*.md'):
            with open(file, 'r', encoding='utf-8') as f:
                documents.append({'type': doc_type, 'source': file.as_posix(), 'text': f.read()})

    print(f'Found {len(documents)} documents')
    return documents

#@retry(wait= wait)
def process_document(document):
    """
    Takes a single Markdown document, splits it using LangChain,
    and uses a local LLM to generate summaries for each section.
    """
    # List to store final Results:
    final_results = []

    # Initializing MarkdownHeaderTextSpliter:
    headers_to_split_on = [
        ('#', 'Header 1'),
        ('##', 'Header 2'),
        ('###', 'Header 3'),
        ('####', 'Header 4'),
        ('#####', 'Header 5'),
    ]

    markdown_splitter = MarkdownHeaderTextSplitter(headers_to_split_on= headers_to_split_on)

    # Splitting the document text:
    splits = markdown_splitter.split_text(document['text'])

    # Looping through each Split:
    for split in splits:

        # 1. System Prompt for LLM:
        system_prompt = """
        You are an expert technical writer and AI assistant for the gradio Python library.
        Your task is to analyze a single section of gradio documentation and extract a concise headline and a brief summary.

        RULES:
        1. The headline should be 3-6 words, highly relevant for search queries.
        2. The summary must be exactly 2-3 sentences explaining what this section covers.
        3. DO NOT include code snippets in your summary.
        4. DO NOT reproduce the original text.
        5. You MUST respond ONLY with valid JSON matching the exact schema below. Do not include markdown formatting like ```json.

        REQUIRED JSON SCHEMA:
        {
            "headline": "A brief, search-optimized heading",
            "summary": "A 2-3 sentence explanation of the concepts covered"
        }
        """

        # 2. User Prompt:
        user_prompt = f"""
        DOCUMENT CONTEXT (Headers):
        {split.metadata}
        
        DOCUMENT TEXT:
        {split.page_content}
        """

        # 3. Message Payload for LLM:
        messages = [
            {'role': 'system', 'content': system_prompt.strip()},
            {'role': 'user', 'content': user_prompt.strip()},
        ]

        # 4. Calling OLLAMA:
        response = completion(
            model= MODEL,
            messages= messages,
            response_format= {'type': 'json_object'},
        )

        # 5. Response from LLM:
        reply_text = response.choices[0].message.content

        # 6. Parsing the JSON string using Pydantic:
        try:
            parsed_json = json.loads(reply_text)
            llm_chunk = Chunk(**parsed_json)
        except Exception as e:
            print(f'Failed to Parse LLM Output: {reply_text}')
            print(f'Error: {e}')
            continue # Skipping the Chunk

        # 7. Merging The LLM Chunk with Original Text:
        result = llm_chunk.as_result(original_text= split.page_content, source_metadata= split.metadata)

        final_results.append(result)

    return final_results

if __name__ == '__main__':
    print('Fetching documents...')
    documents = fetch_document()

    if not documents:
        print('No documents found.')
    else:
        test_doc = documents[0]
        print(f"Testing with document: {test_doc['source']}")

        try:
            results = process_document(test_doc)
            print(f'\nSuccess! Generated {len(results)} chunks from this document.')
            if results:
                print("\n" + "=" * 50)
                print("🔍 INSPECTING THE FIRST CHUNK:")
                print("=" * 50)

                first_result = results[0]
                print(f"\n📍 METADATA (Notice the LangChain headers!):")
                print(first_result.metadata)

                print(f"\n📝 PAGE CONTENT (Headline -> Summary -> Original Text):")
                print("-" * 40)
                print(first_result.page_content)
                print("-" * 40)

        except Exception as e:
            print(f"\n❌ Pipeline failed during testing: {e}")
